#!/usr/bin/env bash
# Transfer file to server

apt-get update
apt-get install nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello Word!" > /etc/nginx/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://github.com/medaminefh;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
