#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html

sed -i "/listen 80 default_server;/a \\\tadd_header X-Served-By \"\$HOSTNAME\";" /etc/nginx/sites-available/default

service nginx restart
