#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
hour=0
while [ "$hour" -lt 13 ];
do
	min=1
	echo "Hour: $hour"
	while [ "$min" -lt 60 ];
	do
		echo "$min"

		((min++))
	done

	((hour++))
done
