#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
c=1
while [ "$c" -lt 11 ];
do
       if [ "$c" -eq 4 ];
       then
	       echo "bad luck"
	 elif [ "$c" -eq 8 ];
	 then
		 echo "good luck"
	 else
		 echo "Best School"
       fi

       ((c++))
done
